### ISSUE TITLE
Can't use self signed cert

### ISSUE THREAD

**Issue by jacobischwartz** [xyu/secure-db-connection#2]
Hello,

I can't for the life of me get Wordpress to connect with self-signed certs. I've generated and installed the certs as described here:
https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-files-using-openssl.html

And I'm specifying the certificate locations in wp-config:

define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL );
define( 'MYSQL_SSL_KEY', '/www/mysql/client-key.pem' );
define( 'MYSQL_SSL_CERT', '/www/mysql/client-cert.pem' );
define( 'MYSQL_SSL_CA', '/www/mysql/ca.pem' );
define( 'MYSQL_SSL_CA_PATH', '/www/mysql/' );
define( 'MYSQL_SSL_CIPHER', 'DHE-RSA-AES256-SHA' );

But I keep getting these errors in my Apache logs and it looks like the ssl mysqli connection is failing and defaulting down to unsecure.

`
PHP Warning:  mysqli_query(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length in /www/vhosts/httpdocs/wp-includes/wp-db.php on line 1887
`

`
PHP Warning:  mysqli_query(): MySQL server has gone away in /www/vhosts/httpdocs/wp-includes/wp-db.php on line 1887
`

`
PHP Warning:  mysqli_query(): Error reading result set's header in /www/vhosts/httpdocs/wp-includes/wp-db.php on line 1887
`

I am able to successfully connect to mysql from the command line using the same certs:
mysql -h <host> -u <user> -p --ssl-mode=REQUIRED --ssl-ca=/www/mysql/ca.pem --ssl-cert=/www/mysql/client-cert.pem --ssl-key=/www/mysql/client-key.pem

I'm running mysql 5.7.20 and php 7.0.24.

Thanks!

**Comment by emfluencekc** [comment]
Update: I think the SSL connections is actually succeeding. I see those connection errors about 10 queries into the page load. When I closely monitor all of the queries, I notice that when the SSL connection fails, Wordpress reconnects to the database (via SSL) and repeats the query.

**Comment by jacobischwartz** [comment]
Update: I think the SSL connections is actually succeeding. I see those connection errors about 10 queries into the page load. When I closely monitor all of the queries, I notice that when the SSL connection fails, Wordpress reconnects to the database (via SSL) and repeats the query.

**Comment by renatonascalves** [comment]
@jacobischwartz So can you close this issue?

**Comment by xyu** [comment]
I'm going to mark this thread as closed it seems like there's an idle timeout and the connection got closed by your database.
