### ISSUE TITLE
Check MYSQL_SSL_CIPHER is empty or not is throwing syntax error

### ISSUE THREAD

**Issue by asharirfan** [xyu/secure-db-connection#5]
## ISSUE
This line https://github.com/xyu/secure-db-connection/blob/master/lib/db.php#L68 in the `db_connect` function returns syntax error in the environment given at the end of the issue.

I investigated further to found out that `! empty( MYSQL_SSL_CIPHER )` is the cause of this error. In the readme file, you have mentioned that this constant contains:

> A list of allowable ciphers to use for SSL encryption

So I figured that empty function is not able to check this constant in this version of PHP.

Can you please suggest a quick fix for this issue?

### Test Environment
PHP version: 5.4.45
MySQL version: 5.5.38

**Comment by xyu** [comment]
@asharirfan thanks for the report! Pushed a fix for this to make the plugin compatible for PHP versions prior to 5.5. Thanks again for the detailed bug report!
